name: pre_build_website
on:
  push:
    branches:
      - master
jobs:
  pre_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: deploy on pre_build branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: pre_build
          enable_jekyll: true
          force_orphan: true
